// Auto-generated by AI Trading Hub scheduled task
// Last updated: July 30, 2026
// DO NOT EDIT MANUALLY — overwritten nightly at 3am
window.TRADING_NEWS = [
  {
    "id": 1,
    "category": "general",
    "title": "New Hedge Funds Are Using AI Bots to Rival Industry Giants",
    "summary": "Five-person hedge fund Palinuro Capital uses LLMs to parse central banker speeches from Hungary to South Korea, work that once required regional specialists, aiming to compete with desks of 20-50 people. Bond-focused firm Osmosis NL now completes research in days that once took weeks with a team of just 15. A Barclays survey of over 400 fixed-income investors found half of long-only managers and a majority of hedge funds use AI daily, mostly for research.",
    "why": "Shows AI is lowering the headcount needed to compete with giant macro funds, letting small boutique shops punch above their weight.",
    "source": "Bloomberg",
    "date": "June 24, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-06-24/new-hedge-funds-are-using-ai-bots-to-rival-industry-giants"
  },
  {
    "id": 2,
    "category": "general",
    "title": "AI Models Could Make Hedge Fund Trading Riskier, Wall Street Researchers Warn",
    "summary": "Studies warn widespread AI adoption could shorten the lifespan of profitable trading signals as investors converge on similar models, and that AI systems can take on more risk than intended or be manipulated through the information they consume. NYU researchers studying nearly a million institutional fund holdings found portfolios have grown increasingly similar as AI adoption spreads, especially among heavy AI users.",
    "why": "A rare, research-backed look at AI's downside in trading — crowded positioning and correlated risk — a needed counterweight to the idea that AI is a guaranteed edge.",
    "source": "Bloomberg",
    "date": "July 1, 2026",
    "url": "https://www.bloomberg.com/news/newsletters/2026-07-01/ai-models-could-make-hedge-fund-trading-riskier-wall-street-researchers-warn"
  },
  {
    "id": 3,
    "category": "stocks",
    "title": "Hedge Fund Magnetar Replaces Humans With AI Bots in New Offering",
    "summary": "The $18 billion firm Magnetar Capital, led by head of AI Quant Trevor Mottl, is launching a fund that uses hundreds of AI bots instead of human analysts to source ideas, analyze stocks, and forecast trends. Human portfolio managers still make the final call on trades. The fund leans toward bullish, buy-and-hold positions, with a smaller sleeve seeking faster market signals.",
    "why": "A concrete example of a major fund restructuring its research process entirely around AI while keeping a human checkpoint for actual trade execution.",
    "source": "Bloomberg",
    "date": "June 9, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-06-09/magnetar-plans-fund-that-replaces-human-analysts-with-ai-bots"
  },
  {
    "id": 4,
    "category": "stocks",
    "title": "Lumenai Plans Launch of Fully Agentic AI Hedge Fund",
    "summary": "Lumenai Investments is launching the Lumenai Innovation Fund, described as the first institutional hedge fund built on a fully agentic AI architecture from day one, with operations expected to begin around June 1, 2026. Autonomous agents originate, evaluate, and risk-manage a global equity long-short strategy continuously, while humans focus on governance and risk oversight rather than picking trades.",
    "why": "Illustrates the next step beyond AI-assisted research — a fund where agents, not analysts, drive day-to-day investment decisions.",
    "source": "Hedgeweek",
    "date": "April 2026",
    "url": "https://www.hedgeweek.com/lumenai-plans-launch-of-fully-agentic-ai-hedge-fund/"
  },
  {
    "id": 5,
    "category": "stocks",
    "title": "Aethon Launches AI-Driven Hedge Fund With $50m in Initial Capital",
    "summary": "Aethon Fund launched with $50 million in capital under founder George Kailas, who spent two decades developing systematic approaches to identify gaps in conventional quant models. The fund combines proprietary market signals, including retail-driven data, with AI-powered trade execution.",
    "why": "A concrete, recent example of a new AI-driven fund entering institutional markets with a specific signal-research background rather than generic AI hype.",
    "source": "Hedgeweek",
    "date": "July 15, 2026",
    "url": "https://www.hedgeweek.com/aethon-launches-ai-driven-hedge-fund-with-50m-in-initial-capital/"
  },
  {
    "id": 6,
    "category": "stocks",
    "title": "China Quant Funds Draw Billions as AI Trounces Human Traders",
    "summary": "Chinese quant fund assets more than doubled to roughly 2.6 trillion yuan (about $384 billion) in under a year as AI-driven, long-only stock strategies beat discretionary managers by 20.3 percentage points, gaining 44.7% over the period. Ubiquant raised $384 million for a new fund in under two hours in May amid the investor rush.",
    "why": "Real-money evidence that AI-driven quant strategies can meaningfully outperform human stock pickers at scale, and how quickly capital chases that performance.",
    "source": "Bloomberg",
    "date": "July 2, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-02/china-quant-funds-draw-billions-as-ai-trounces-human-traders"
  },
  {
    "id": 7,
    "category": "general",
    "title": "China Considers Oversight of Quant Funds, AI Trading After CSRC Consultations",
    "summary": "Following steep losses at Chinese quant funds and a month-long tech-stock selloff, the China Securities Regulatory Commission held back-to-back consultations with investors and listed companies, shifting its language from regulating the \"development\" of quant and AI trading to regulating specific \"behaviors\" — a signal that concrete rules may follow to prevent AI from amplifying market volatility.",
    "why": "The necessary counterpoint to AI-driven quant success stories: regulators stepping in once AI strategies contributed to a sharp market drawdown.",
    "source": "Bloomberg",
    "date": "July 23, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-23/china-hints-at-regulations-on-quants-ai-usage-in-state-paper"
  },
  {
    "id": 8,
    "category": "crypto",
    "title": "How AI Is Helping Retail Traders Exploit Prediction Market 'Glitches' to Make Easy Money",
    "summary": "A fully automated bot executed 8,894 trades on five-minute Bitcoin and Ether prediction markets, exploiting brief moments when \"Yes\" and \"No\" contract prices summed to less than $1, netting nearly $150,000 at roughly a 1.5%-3% edge per trade. Thin order-book depth of only $5,000-$15,000 per side currently limits the strategy to small, nimble traders rather than large trading desks.",
    "why": "A concrete, numbers-backed example of a retail-accessible AI arbitrage strategy in crypto prediction markets, including a clear explanation of why the edge is self-limiting.",
    "source": "CoinDesk",
    "date": "February 21, 2026",
    "url": "https://www.coindesk.com/markets/2026/02/21/how-ai-is-helping-retail-traders-exploit-prediction-market-glitches-to-make-easy-money"
  },
  {
    "id": 9,
    "category": "crypto",
    "title": "As Crypto Trading Platforms Race to Deploy AI Agents, Here's What a Nasdaq Engineer Is Seeing",
    "summary": "Nasdaq has sharply expanded its use of AI agents over the past 18 months across market surveillance, compliance, and its SEC-approved Dynamic M-ELO AI order type. Nasdaq researcher Pranav Ramesh expects crypto trading platforms to lead the way on retail-facing AI agents for trade analysis and execution support, though he says systems still stop short of full autonomy, with humans retaining final approval.",
    "why": "Connects institutional-grade AI trading infrastructure already live at Nasdaq to what's likely coming next for retail crypto traders.",
    "source": "CoinDesk",
    "date": "March 19, 2026",
    "url": "https://www.coindesk.com/business/2026/03/19/crypto-trading-platforms-race-to-deploy-ai-agents-job-losses-to-artificial-intelligence-will-continue-to-mount"
  },
  {
    "id": 10,
    "category": "general",
    "title": "AI in Investment Management: 2026 Outlook (Part II)",
    "summary": "Two Sigma researchers caution that AI does not solve quant investing's core problem: predicting the future from past data without overfitting to backtests or regime changes. They argue this challenge actually gets harder with powerful AI, since agents can rapidly generate and backtest huge numbers of hypotheses, worsening overfitting risk, and pretrained LLMs may implicitly \"know\" about historical regime shifts baked into their training data, undermining backtest validity.",
    "why": "A rare, unhyped admission from a top quant firm about AI's real limitations in generating durable trading edge, directly countering \"AI guarantees alpha\" narratives.",
    "source": "Two Sigma",
    "date": "January 21, 2026",
    "url": "https://www.twosigma.com/articles/ai-in-investment-management-2026-outlook-part-ii/"
  }
];
