// Auto-generated by AI Trading Hub scheduled task
// Last updated: 2026-07-23 03:00 (scheduled run)
// DO NOT EDIT MANUALLY — overwritten nightly at 3am
window.TRADING_NEWS = [
  {
    "id": 1,
    "category": "general",
    "title": "Magnetar Plans Fund That Replaces Human Analysts With AI Bots",
    "summary": "Magnetar Capital, the $18 billion hedge fund firm, is preparing to launch a new offering that deploys hundreds of AI bots to research stocks instead of human analysts. The fund is expected to launch later this year and represents one of the most ambitious attempts yet by a hedge fund to integrate AI into the core investment process.",
    "why": "A major, established fund is betting its core research process on AI agents rather than just augmenting human analysts — a bellwether for how far the industry is willing to go.",
    "source": "Bloomberg",
    "date": "June 9, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-06-09/magnetar-plans-fund-that-replaces-human-analysts-with-ai-bots"
  },
  {
    "id": 2,
    "category": "general",
    "title": "Aethon Launches AI-Driven Hedge Fund With $50m in Initial Capital",
    "summary": "Aethon Fund has launched with $50 million in initial capital, seeking to attract institutional investors with a systematic investment strategy that combines proprietary market signals with artificial-intelligence-driven trade execution.",
    "why": "Shows how smaller, AI-native funds are entering the market to compete with established players by pairing systematic signals with AI-driven execution.",
    "source": "Hedgeweek",
    "date": "2026",
    "url": "https://www.hedgeweek.com/aethon-launches-ai-driven-hedge-fund-with-50m-in-initial-capital/"
  },
  {
    "id": 3,
    "category": "stocks",
    "title": "China Quant Funds Draw Billions as AI Trounces Human Traders",
    "summary": "Quant funds in China have drawn a flood of investor money, with firms like Ubiquant raising 2.6 billion yuan (about $384 million) in less than two hours for a new fund. AI-driven systematic strategies have been outperforming human stock-pickers.",
    "why": "Concrete capital-flow evidence that AI-driven quant strategies are winning investor trust and real money in one of the world's largest equity markets.",
    "source": "Bloomberg",
    "date": "July 2, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-02/china-quant-funds-draw-billions-as-ai-trounces-human-traders"
  },
  {
    "id": 4,
    "category": "stocks",
    "title": "China Quant Funds See Steep Drawdowns After AI Stock Rout Deepens",
    "summary": "A fund linked to DeepSeek's founder slumped 16% as a broader selloff hit China's quant funds amid a deepening rout in AI-related stocks.",
    "why": "An honest, concrete counterpoint to AI-trading hype: quant strategies tied to AI themes can suffer sharp drawdowns just like any other strategy.",
    "source": "Bloomberg",
    "date": "July 20, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-20/deepseek-founder-s-fund-slumps-16-as-ai-rout-hits-china-quants"
  },
  {
    "id": 5,
    "category": "general",
    "title": "AI Models Could Make Hedge Fund Trading Riskier, Wall Street Researchers Warn",
    "summary": "Wall Street researchers are warning that widespread hedge fund adoption of AI models could increase trading risk, as funds increasingly weave large language models into research and trading decisions across the industry.",
    "why": "A sober, non-hype risk assessment — correlated AI-driven positioning across many funds could amplify systemic risk rather than reduce it.",
    "source": "Bloomberg",
    "date": "July 1, 2026",
    "url": "https://www.bloomberg.com/news/newsletters/2026-07-01/ai-models-could-make-hedge-fund-trading-riskier-wall-street-researchers-warn"
  },
  {
    "id": 6,
    "category": "stocks",
    "title": "Quant Hedge Funds Extend Worst Run Since 2023 as Momentum Slides",
    "summary": "Quantitative hedge funds are enduring their worst stretch since 2023 as a violent rotation in the stock market causes momentum-based strategies to drop more than 3% for a second straight week.",
    "why": "A direct, real-world limitation of systematic and AI-assisted strategies: momentum models can break down quickly when market regimes shift.",
    "source": "Bloomberg",
    "date": "July 6, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-06/quant-hedge-funds-extend-worst-run-since-2023-as-momentum-slides"
  },
  {
    "id": 7,
    "category": "crypto",
    "title": "How AI Is Helping Retail Traders Exploit Prediction Market 'Glitches' to Make Easy Money",
    "summary": "A fully automated bot executed 8,894 trades on short-term crypto prediction markets, exploiting brief moments when 'Yes' and 'No' contract prices summed to less than $1, netting nearly $150,000 at a 1.5%-3% edge per trade. Thin order-book depth ($5,000-$15,000 per side) means the strategy only works at small scale.",
    "why": "A concrete, retail-accessible example of AI-driven arbitrage, paired with an honest limitation: the edge disappears once real capital tries to scale it up.",
    "source": "CoinDesk",
    "date": "February 21, 2026",
    "url": "https://www.coindesk.com/markets/2026/02/21/how-ai-is-helping-retail-traders-exploit-prediction-market-glitches-to-make-easy-money"
  },
  {
    "id": 8,
    "category": "crypto",
    "title": "As Crypto Trading Platforms Race to Deploy AI Agents, Here's What a Nasdaq Engineer Is Seeing",
    "summary": "Nasdaq has sharply expanded its use of AI agents over the past 18 months across market surveillance, compliance, and microstructure analysis, including its SEC-approved Dynamic M-ELO order type, which uses over 140 factors to adjust to real-time market conditions. A Nasdaq researcher expects crypto platforms to lead retail-facing AI trading tools, even as AI-driven layoffs hit firms like Crypto.com, Messari, and Block.",
    "why": "Details a real, regulator-approved AI trading system already in production, plus a candid look at how AI is reshaping trading-industry jobs, not just returns.",
    "source": "CoinDesk",
    "date": "March 19, 2026",
    "url": "https://www.coindesk.com/business/2026/03/19/crypto-trading-platforms-race-to-deploy-ai-agents-job-losses-to-artificial-intelligence-will-continue-to-mount"
  },
  {
    "id": 9,
    "category": "general",
    "title": "FinBERT: A Large Language Model for Extracting Information From Financial Text",
    "summary": "A January 2026 HKUST Business School paper found that FinBERT captures 18% more textual informativeness from earnings-call transcripts than baseline NLP models, and is better at correctly identifying sentiment in sentences other algorithms mislabel as neutral.",
    "why": "Quantifies a concrete technical improvement in NLP-based financial sentiment extraction, a building block behind many AI trading signals.",
    "source": "HKUST Business School",
    "date": "January 2026",
    "url": "https://bm.hkust.edu.hk/bizinsight/2026/01/finbert-large-language-model-extracting-information-financial-text"
  },
  {
    "id": 10,
    "category": "general",
    "title": "Agentic Trading: When LLM Agents Meet Financial Markets",
    "summary": "An academic survey describes how large language models have become core components of trading agents since 2024-2026 — serving as memory modules, factor proposers, policy backbones, and sentiment-signal generators. Frameworks like FinRL-DeepSeek and MacroHFT combine LLM-based priors with reinforcement learning, reporting improved risk-adjusted returns over baselines in backtests.",
    "why": "A technical overview of how researchers are currently combining LLMs with reinforcement learning for trading — a preview of where retail AI trading tools may head next.",
    "source": "arXiv",
    "date": "2026",
    "url": "https://arxiv.org/pdf/2605.19337"
  }
];
