// Auto-generated by AI Trading Hub scheduled task
// Last updated: July 28, 2026, 07:10 UTC
// DO NOT EDIT MANUALLY — overwritten nightly at 3am
window.TRADING_NEWS = [
  {
    "id": 1,
    "category": "stocks",
    "title": "Millennium-Backed Trader Gains 61% With Bets on AI Backbone",
    "summary": "A trader backed by Millennium Management posted a 61% gain in 2026 by concentrating bets on the 'AI backbone' — memory chip makers and infrastructure suppliers benefiting from the AI buildout. The gains came largely from the memory chip boom tied to AI data center demand.",
    "why": "Shows how a specific, well-defined AI infrastructure thesis (memory/chips) can produce outsized returns for a real multi-strategy hedge fund trader, not just a backtest.",
    "source": "Bloomberg",
    "date": "July 6, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-06/millennium-backed-trader-gains-61-with-bets-on-ai-backbone"
  },
  {
    "id": 2,
    "category": "stocks",
    "title": "China Quant Funds Draw Billions as AI Trounces Human Traders",
    "summary": "Chinese quant funds are pulling in massive investor inflows as AI-driven systematic strategies outperform human stock-pickers; Ubiquant reportedly raised 2.6 billion yuan (about $384 million) for a new fund in under two hours.",
    "why": "Concrete evidence of capital actively rotating from discretionary to AI-driven systematic strategies based on realized performance, not hype.",
    "source": "Bloomberg",
    "date": "July 2, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-02/china-quant-funds-draw-billions-as-ai-trounces-human-traders"
  },
  {
    "id": 3,
    "category": "general",
    "title": "China Considers Oversight of Quant Funds, AI Trading After CSRC Consultations",
    "summary": "China's securities regulator (CSRC) held an unusually large number of consultations with investors, listed companies, and experts over two days, signaling that new rules may be coming for quant funds' use of AI in trading.",
    "why": "Regulatory scrutiny at this scale shows AI-driven trading has grown large enough to worry systemic-risk regulators — a key signal for anyone tracking where AI trading policy is headed.",
    "source": "Bloomberg",
    "date": "July 23, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-23/china-hints-at-regulations-on-quants-ai-usage-in-state-paper"
  },
  {
    "id": 4,
    "category": "stocks",
    "title": "Goldman Becomes Taiwan's Top Foreign Broker on AI Quant Push",
    "summary": "Goldman Sachs overtook Wall Street rivals to become the top foreign equity broker in Taiwan, driven by surging demand from quant funds seeking AI-related exposure in the semiconductor supply chain.",
    "why": "Demonstrates how AI-driven quant demand is reshaping brokerage market share around key AI hardware exchanges, not just software or model providers.",
    "source": "Bloomberg",
    "date": "July 8, 2026",
    "url": "https://www.bloomberg.com/news/articles/2026-07-08/goldman-becomes-taiwan-s-top-foreign-broker-on-ai-quant-push"
  },
  {
    "id": 5,
    "category": "general",
    "title": "Man Group Deploys Agentic AI for Quant Signal Discovery",
    "summary": "Man Group, which manages roughly $228.7 billion, is using an internal system called AlphaGPT that proposes trading signals, writes the code, and runs backtests before any human reviews the output.",
    "why": "A concrete, named example of how a major systematic fund is automating its research pipeline with agentic AI while keeping human review as a final check.",
    "source": "Hedgeweek",
    "date": "July 2026",
    "url": "https://www.hedgeweek.com/man-group-deploys-agentic-ai-for-quant-signal-discovery/"
  },
  {
    "id": 6,
    "category": "general",
    "title": "AI Models Could Make Hedge Fund Trading Riskier, Wall Street Researchers Warn",
    "summary": "Wall Street researchers cautioned that widespread hedge fund adoption of similar AI models could increase correlated trading behavior across firms, amplifying market risk during stress events.",
    "why": "An honest, research-backed warning that AI adoption can create systemic risk through herding, an important counterweight to purely bullish AI-trading coverage.",
    "source": "Bloomberg",
    "date": "July 1, 2026",
    "url": "https://www.bloomberg.com/news/newsletters/2026-07-01/ai-models-could-make-hedge-fund-trading-riskier-wall-street-researchers-warn"
  },
  {
    "id": 7,
    "category": "general",
    "title": "Two Sigma Bolsters AI Capabilities With Senior Hire From Goldman Sachs",
    "summary": "Two Sigma strengthened its AI and machine learning team by hiring Francesco Maria Delle Fave from Goldman Sachs as a senior vice president in London, working on AI- and ML-driven tools for the firm's research platform.",
    "why": "Shows how top quant firms are competing for AI talent from major banks to build out research infrastructure, a leading indicator of where investment is flowing.",
    "source": "Hedgeweek",
    "date": "January 2026",
    "url": "https://www.hedgeweek.com/two-sigma-bolsters-ai-capabilities-with-senior-hire-from-goldman-sachs/"
  },
  {
    "id": 8,
    "category": "crypto",
    "title": "How AI Is Helping Retail Traders Exploit Prediction Market 'Glitches' to Make Easy Money",
    "summary": "The article describes how retail traders are using AI tools to spot short-lived pricing inefficiencies, or 'glitches,' on prediction markets and profit from them before they're corrected.",
    "why": "A rare example of AI tools giving retail traders — not just institutions — a genuine, accessible edge in a fast-moving market.",
    "source": "CoinDesk",
    "date": "February 21, 2026",
    "url": "https://www.coindesk.com/markets/2026/02/21/how-ai-is-helping-retail-traders-exploit-prediction-market-glitches-to-make-easy-money"
  },
  {
    "id": 9,
    "category": "crypto",
    "title": "As Crypto Trading Platforms Race to Deploy AI Agents, Job Losses to AI Will Continue to Mount",
    "summary": "Crypto trading platforms are racing to deploy AI agents for market analysis and trade execution support, a shift industry watchers say will keep displacing human trading and analysis roles.",
    "why": "Highlights the retail-facing AI-agent trend in crypto trading alongside its labor-market consequences, a two-sided view often missing from crypto AI coverage.",
    "source": "CoinDesk",
    "date": "March 19, 2026",
    "url": "https://www.coindesk.com/business/2026/03/19/crypto-trading-platforms-race-to-deploy-ai-agents-job-losses-to-artificial-intelligence-will-continue-to-mount"
  },
  {
    "id": 10,
    "category": "general",
    "title": "An AI-Powered Flash Crash Is Coming. The Market Isn't Ready.",
    "summary": "The article argues that growing reliance on correlated AI trading models raises the risk of a rapid, AI-driven flash crash, and that current market safeguards and circuit breakers aren't designed for AI-speed, correlated selling.",
    "why": "An honest, cautionary look at systemic risk from widespread automated trading — useful context beyond AI-trading hype.",
    "source": "24/7 Wall St.",
    "date": "July 10, 2026",
    "url": "https://247wallst.com/investing/2026/07/10/an-ai-powered-flash-crash-is-coming-the-market-isnt-ready/"
  },
  {
    "id": 11,
    "category": "stocks",
    "title": "Whale Rock Posts 72.5% YTD Gain as AI and Semiconductor Bets Drive Returns",
    "summary": "Hedge fund Whale Rock posted a 72.5% year-to-date gain in 2026, driven by concentrated positions in AI and semiconductor stocks during the first half of the year's rally.",
    "why": "Concrete, named performance data showing how much upside concentrated AI-themed positioning delivered before the July 2026 pullback — useful for weighing the risk/reward of similar bets.",
    "source": "Hedgeweek",
    "date": "July 2026",
    "url": "https://www.hedgeweek.com/whale-rock-posts-72-5-ytd-gain-as-ai-and-semiconductor-bets-drive-returns/"
  }
];
